[workspace]
name = "goldeneye-0.1.0-consumer"
channels = [
  "https://conda.anaconda.org/anderslanglands/label/test",
  "https://conda.anaconda.org/anderslanglands",
  "conda-forge",
]
platforms = ["linux-64"]
channel-priority = "disabled"

[feature.goldeneye.dependencies]
goldeneye = "==0.1.0"
openusd-typhoon = "*"

[environments]
goldeneye = ["goldeneye"]
