[workspace]
name = "materialx-1.39.5-consumer"
channels = [
  "https://conda.anaconda.org/anderslanglands/label/test",
  "https://conda.anaconda.org/anderslanglands",
  "conda-forge",
]
platforms = ["linux-64", "win-64", "osx-arm64"]
channel-priority = "strict"

[feature.materialx-lib.dependencies]
materialx-lib = "==1.39.5"

[feature.materialx-dev.dependencies]
materialx-dev = "==1.39.5"

[feature.materialx-python.dependencies]
materialx-python = "==1.39.5"

[feature.materialx.dependencies]
materialx = "==1.39.5"

[environments]
materialx-lib = ["materialx-lib"]
materialx-dev = ["materialx-dev"]
materialx-python = ["materialx-python"]
materialx = ["materialx"]
