[workspace]
name = "goldeneye-0.8.0-consumer"
channels = [
  "https://conda.anaconda.org/anderslanglands",
  "conda-forge",
]
platforms = ["linux-64", "win-64", "osx-arm64"]
channel-priority = "strict"

[feature.goldeneye.dependencies]
goldeneye = "==0.8.0"
openusd-typhoon = "*"

[environments]
goldeneye = ["goldeneye"]
