[workspace]
name = "openusd-typhoon-26.05.0beaac8-consumer"
channels = [
  "https://conda.anaconda.org/anderslanglands/label/test",
  "https://conda.anaconda.org/anderslanglands",
  "conda-forge",
]
platforms = ["linux-64"]
channel-priority = "disabled"

[dependencies]
openusd-typhoon = "==26.05.0beaac8"
