[workspace]
name = "openimageio-3.1.14.0-consumer"
channels = [
  "https://conda.anaconda.org/anderslanglands/label/test",
  "https://conda.anaconda.org/anderslanglands",
  "conda-forge",
]
platforms = ["linux-64"]
channel-priority = "strict"

[feature.openimageio-lib.dependencies]
openimageio-lib = "==3.1.14.0"

[feature.openimageio-dev.dependencies]
openimageio-dev = "==3.1.14.0"

[feature.openimageio-tools.dependencies]
openimageio-tools = "==3.1.14.0"

[feature.openimageio-python.dependencies]
openimageio-python = "==3.1.14.0"

[feature.openimageio-format-gif.dependencies]
openimageio-format-gif = "==3.1.14.0"

[feature.openimageio-format-webp.dependencies]
openimageio-format-webp = "==3.1.14.0"

[feature.openimageio-format-jpeg2000.dependencies]
openimageio-format-jpeg2000 = "==3.1.14.0"

[feature.openimageio-format-jpegxl.dependencies]
openimageio-format-jpegxl = "==3.1.14.0"

[feature.openimageio-format-heif.dependencies]
openimageio-format-heif = "==3.1.14.0"

[feature.openimageio-format-raw.dependencies]
openimageio-format-raw = "==3.1.14.0"

[feature.openimageio-format-dicom.dependencies]
openimageio-format-dicom = "==3.1.14.0"

[feature.openimageio-format-ffmpeg.dependencies]
openimageio-format-ffmpeg = "==3.1.14.0"

[feature.openimageio-format-openvdb.dependencies]
openimageio-format-openvdb = "==3.1.14.0"

[feature.openimageio.dependencies]
openimageio = "==3.1.14.0"

[environments]
openimageio-lib = ["openimageio-lib"]
openimageio-dev = ["openimageio-dev"]
openimageio-tools = ["openimageio-tools"]
openimageio-python = ["openimageio-python"]
openimageio-format-gif = ["openimageio-format-gif"]
openimageio-format-webp = ["openimageio-format-webp"]
openimageio-format-jpeg2000 = ["openimageio-format-jpeg2000"]
openimageio-format-jpegxl = ["openimageio-format-jpegxl"]
openimageio-format-heif = ["openimageio-format-heif"]
openimageio-format-raw = ["openimageio-format-raw"]
openimageio-format-dicom = ["openimageio-format-dicom"]
openimageio-format-ffmpeg = ["openimageio-format-ffmpeg"]
openimageio-format-openvdb = ["openimageio-format-openvdb"]
openimageio = ["openimageio"]
