if(NOT DEFINED PARTIO_SOURCE_DIR)
  message(FATAL_ERROR "PARTIO_SOURCE_DIR is required")
endif()

set(_partio_python_cmake "${PARTIO_SOURCE_DIR}/src/py/CMakeLists.txt")
file(READ "${_partio_python_cmake}" _contents)

set(_old_link [=[target_link_libraries(partio_mod PRIVATE ${Python_LIBRARIES} partio)]=])
set(_new_link [=[if(APPLE)
    target_link_libraries(partio_mod PRIVATE partio)
    target_link_options(partio_mod PRIVATE "-undefined" "dynamic_lookup")
else()
    target_link_libraries(partio_mod PRIVATE ${Python_LIBRARIES} partio)
endif()]=])

string(FIND "${_contents}" "${_old_link}" _old_link_pos)
if(NOT _old_link_pos EQUAL -1)
  string(REPLACE "${_old_link}" "${_new_link}" _contents "${_contents}")
  file(WRITE "${_partio_python_cmake}" "${_contents}")
else()
  string(FIND "${_contents}" "target_link_options(partio_mod PRIVATE \"-undefined\" \"dynamic_lookup\")" _patched_link_pos)
  if(_patched_link_pos EQUAL -1)
    message(FATAL_ERROR "Could not find Partio Python link line to patch")
  endif()
endif()
