if(NOT DEFINED OPENSD_CONFIG)
  message(FATAL_ERROR "OPENSD_CONFIG is required")
endif()

if(NOT EXISTS "${OPENSD_CONFIG}")
  message(FATAL_ERROR "OpenSubdiv config does not exist: ${OPENSD_CONFIG}")
endif()

file(READ "${OPENSD_CONFIG}" _opensubdiv_config_contents)
set(_opensubdiv_targets [[include("${CMAKE_CURRENT_LIST_DIR}/OpenSubdivTargets.cmake")]])

set(_opensubdiv_injected "include(CMakeFindDependencyMacro)\n")
foreach(_opensubdiv_dep IN LISTS OPENSD_FIND_DEPENDENCIES)
  string(APPEND _opensubdiv_injected "find_dependency(${_opensubdiv_dep})\n")
endforeach()
string(APPEND _opensubdiv_injected "${_opensubdiv_targets}\n")

if(DEFINED OPENSD_TARGET_DEFINITIONS AND NOT OPENSD_TARGET_DEFINITIONS STREQUAL "")
  string(APPEND _opensubdiv_injected "foreach(_opensubdiv_gpu_target IN ITEMS OpenSubdiv::osdGPU OpenSubdiv::osdGPU_static)\n")
  string(APPEND _opensubdiv_injected "  if(TARGET \${_opensubdiv_gpu_target})\n")
  string(APPEND _opensubdiv_injected "    target_compile_definitions(\${_opensubdiv_gpu_target} INTERFACE ${OPENSD_TARGET_DEFINITIONS})\n")
  string(APPEND _opensubdiv_injected "  endif()\n")
  string(APPEND _opensubdiv_injected "endforeach()\n")
endif()

string(REPLACE "${_opensubdiv_targets}" "${_opensubdiv_injected}" _opensubdiv_patched_contents "${_opensubdiv_config_contents}")
if(_opensubdiv_patched_contents STREQUAL _opensubdiv_config_contents)
  message(FATAL_ERROR "Failed to patch OpenSubdiv target include in ${OPENSD_CONFIG}")
endif()
file(WRITE "${OPENSD_CONFIG}" "${_opensubdiv_patched_contents}")
