[workspace]
name = "mitsuba-3.8.0-consumer"
channels = [
  "https://conda.anaconda.org/anderslanglands/label/test",
  "https://conda.anaconda.org/anderslanglands",
  "conda-forge",
]
platforms = ["linux-64", "win-64", "osx-arm64"]
channel-priority = "strict"

[feature.mitsuba-python.dependencies]
mitsuba-python = "==3.8.0"

[feature.mitsuba-tools.dependencies]
mitsuba-tools = "==3.8.0"

[feature.mitsuba.dependencies]
mitsuba = "==3.8.0"

[environments]
mitsuba-python = ["mitsuba-python"]
mitsuba-tools = ["mitsuba-tools"]
mitsuba = ["mitsuba"]
