[workspace]
name = "pbrt-4.0.0-consumer"
channels = [
  "https://conda.anaconda.org/anderslanglands/label/test",
  "https://conda.anaconda.org/anderslanglands",
  "conda-forge",
]
platforms = ["linux-64"]
channel-priority = "strict"

[feature.pbrt.dependencies]
pbrt = "==4.0.0"

[feature.pbrt-optix.dependencies]
pbrt-optix = "==4.0.0"

[environments]
pbrt = ["pbrt"]
pbrt-optix = ["pbrt-optix"]
