[workspace]
name = "libuhdr-2.0.2-consumer"
channels = [
  "https://conda.anaconda.org/anderslanglands",
  "conda-forge",
]
platforms = ["linux-64"]
channel-priority = "strict"

[feature.libuhdr-lib.dependencies]
libuhdr-lib = "==2.0.2"

[feature.libuhdr-dev.dependencies]
libuhdr-dev = "==2.0.2"

[feature.libuhdr.dependencies]
libuhdr = "==2.0.2"

[environments]
libuhdr-lib = ["libuhdr-lib"]
libuhdr-dev = ["libuhdr-dev"]
libuhdr = ["libuhdr"]
